services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./backend
    container_name: app
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'


